### ISSUE TITLE
add version number to released dll

### ISSUE THREAD

**Issue by plaxdan** [DataSplice/datasplice-plugin-esri-datasource#14]
Adding the version to the filename could cause problems when unzipping a new GIS release onto the server because we'd eventually get two EsriDataSourcePlugin_vX.X.X.dll files on the same server. Instead we could consider leaving the filename the same with each release but modifying the dll metadata instead:

![image](https://cloud.githubusercontent.com/assets/382348/5491886/eb9dbe34-8699-11e4-9bab-502e89b9fb2a.png)

**Comment by mjohnson-github** [comment]
Michelle @ CSU is requesting that the *.dll version number match the build number. They rely on that information when checking server setups etc..

**Comment by kenfletcher** [comment]
Hi Mike, just checking in
they look like they have version numbers to me?
what dll are you talking about?  and maybe they have some developer
customization? is build number zero?

**Comment by plaxdan** [comment]
@kenfletcher Mike is saying that Michelle would like the version number in the properties of the DLL to match the Jenkins build number for the release:

![image](https://cloud.githubusercontent.com/assets/382348/9122624/7dbc084e-3c47-11e5-93d0-c71425521b2d.png)

I'm working on this now.

**Comment by kenfletcher** [comment]
never mind, missed the work esri

**Comment by plaxdan** [comment]
...and the fact that this issue is on the `datasplice-plugin-esri-datasource` repo ;-)

**Comment by kenfletcher** [comment]
someone around here needs to get used to wearing his new glasses :)

**Comment by plaxdan** [comment]
Jenkins config [has been adjusted](https://github.com/DataSplice/internal-projects/commit/f457dff684c5502555b27daf9ad5fcf829e7b9cb) to add the `BUILD_ID` to the `.dll`:

![image](https://cloud.githubusercontent.com/assets/382348/9124843/0288275a-3c58-11e5-92ce-c03afba6e848.png)

Build [16](https://dev.datasplice.com/jenkins/job/datasplice-gis-plugins/16/deployedArtifacts/) is identical to [15](https://dev.datasplice.com/jenkins/job/datasplice-gis-plugins/15/deployedArtifacts/) except for the dll version number.
